language: node_js
node_js:
- "10"

cache:
  yarn: true
  directories:
  - node_modules

before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.3
- export PATH="$HOME/.yarn/bin:$PATH"

install:
- yarn

script:
- yarn lint
- yarn test
- rm -rf dist
- yarn build

after_success:
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then ./release-to-github-pages.sh; fi
